### ISSUE TITLE
External Links not handled

### ISSUE THREAD

**Issue by Eeems** [dps/remarkable-wikipedia#12]
External links are clickable but will result in an error. Not really sure the best way to handle this. Ideally we could hand off to a generic browser for this kind of thing, but it might make more sense to just give a more user friendly message and maybe provide a QR code so they can use their phone to look at the site?
![2021-03-10T102157 347](https://user-images.githubusercontent.com/1176979/110670304-7ac2f880-818a-11eb-9897-a035318ba42f.png)

**Comment by dps** [comment]
Decided to let the app actually try to load external URLs (only one level deep). Some pages work well, seems reasonable to give you a chance to try to load it

**Comment by dps** [comment]
It's a bit janky, but useful...

**Comment by Eeems** [comment]
Awesome! I might ~~steal~~ borrow some of this project to write a very simple web browser.
