### ISSUE TITLE
Add pen support

### ISSUE THREAD

**Issue by Eeems** [dps/remarkable-wikipedia#15]
I've hacked in pen support into Oxide:
https://github.com/Eeems/oxide/blob/master/shared/eventfilter.h
https://github.com/Eeems/oxide/blob/master/shared/eventfilter.cpp
https://github.com/Eeems/oxide/blob/master/applications/launcher/main.cpp#L52-L57

It doesn't handle some dynamic content mouse areas though due to my [widgetsAt](https://github.com/Eeems/oxide/blob/master/shared/eventfilter.cpp#L55-L73) implementation not working properly. It also doesn't properly detect/handle when one mouse area is over top of another.

**Comment by dps** [comment]
Fixed in PR #16 Thanks for the pointers!
