### ISSUE TITLE
Install.sh couple issues

### ISSUE THREAD

**Issue by artelse** [dps/remarkable-wikipedia#2]
`Install.sh` misses the following line to copy `fingerterm` binary:
`scp fingerterm root@$IP:/usr/bin/fingerterm`

The last reboot command doesn't work, but this will:
`ssh root@$IP "shutdown -r 0"`

**Comment by F1LT3R** [comment]
After running the install script I was no longer able to run keywriter.

```
./keywriter
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
File open for reading.
Segmentation fault (core dumped)
```

I get `Segmentation fault (core dumped)` for everything in this project's `bin/` directory.

**Comment by robertkeizer** [comment]
I attempted to get this functional for a few minutes as well.. similar results. Pretty sure the binaries that are build are simply not compatible with the update that rolled out a few months ago.

**Comment by cowpod** [comment]
You should manually install wikipedia (though currently it doesn't work for newer ZIM files or remarkable 2), and then install keywriter and draft/oxide/remux using toltec opkg.

**Comment by dps** [comment]
The app is now packaged with toltec
