### ISSUE TITLE
Address bar doesn't work

### ISSUE THREAD

**Issue by Richardxm2062** [dps/remarkable-wikipedia#3]
After I installed this software, I tried to search something in wikipedia to test whether it works well.(for example:Apple)
But the suggestions didn't appear. It was blank below the address bar.
The version of my remarkable is 2.2.0.48

**Comment by cowpod** [comment]
Hey, same here. After updating the zimserver binary I can get the zim file to load, however I can't get the keyboard to show up at all.
Remarkable 2, 2.5.1.45

**Comment by dps** [comment]
Fixed
