### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by matteodelabre** [dps/remarkable-wikipedia#4]
Thanks for your app! Since it is currently not licensed for redistribution, we cannot package it in the [Toltec repository](https://github.com/toltec-dev/toltec). Do you plan on adding a free software license to your project?

**Comment by Eeems** [comment]
It looks like https://github.com/dps/remarkable-wikipedia/pull/5 solves this

**Comment by cowpod** [comment]
You'll need a license for each other binary included . Also, all unrelated binaries such as draft and keywriter will need to be removed before this can be added to toltec.

It wouldn't work to "opkg install wikipedia" and then overwrite your existing launcher... or install something you didn't want to.

**Comment by Eeems** [comment]
> You'll need a license for each other binary included . Also, all unrelated binaries such as draft and keywriter will need to be removed before this can be added to toltec.
> 
> It wouldn't work to "opkg install wikipedia" and then overwrite your existing launcher... or install something you didn't want to.

We can deal with that at package time in toltec itself.

**Comment by Eeems** [comment]
@matteodelabre looks like this can be closed?

**Comment by dps** [comment]
resolved
