### ISSUE TITLE
Question: Gesture ready?

### ISSUE THREAD

**Issue by queesamor** [dps/remarkable-wikipedia#6]
I have an RM2, but your readme makes multiple references to using the hardware buttons for UI. Can everything be done using the gestures present in recent versions of the OS, since my device has no physical buttons?

**Comment by cowpod** [comment]
Would be great to have left/right page back/forward, and then up/down scroll.
Also, there doesn't appear to be a way to exit this either - so maybe a swipe down from very top of screen?

**Comment by dps** [comment]
Is now using gestures for scroll and a proper keyboard

**Comment by dps** [comment]
*** Is NOW using - this issue is fixed
