### ISSUE TITLE
zimserver and qtwikipedia need updating

### ISSUE THREAD

**Issue by cowpod** [dps/remarkable-wikipedia#7]
File wikipedia_en_simple_all_nopic_2021_02.zim fails to open with error emssage "zim: unsupported cluster compression".
It appears that zimserver needs to be rebuilt from https://github.com/tim-st/go-zim to support these newer zim files, but I do not know how to compile zimserver for arm.

Remarkable 2, 2.5.1.45

**Comment by cowpod** [comment]
I've compiled the latest zimserver, and replaced the binary at /usr/bin/zimserver. 
Wikipedia does load, however the app itself is unusable; large pieces of text are missing, and the keyboard for the search bar never shows up.

Is there a way to get logs?

[zimserver.zip](https://github.com/dps/remarkable-wikipedia/files/6096534/zimserver.zip)

**Comment by dps** [comment]
On remarkable v2 this is a known issue with the  frame buffer driver (it
doesn’t display blue text). I will take a look at a fix tomorrow

**Comment by dps** [comment]
The version on the "blacklinks" branch now renders the links and keyboard correctly on rm2 but there's quite a bit more work to make this rm2 ready given it relies pretty heavily on the hardware keys on rm1. I'll work on it this week.

![IMG_9296](https://user-images.githubusercontent.com/237355/110286108-302e5a00-7f99-11eb-8afd-74a8492b89bf.png)

**Comment by dps** [comment]
I also haven't been able to get an external SD card working with rm2 so we're limited to zim files that fit on the local storage. I therefore am considering making this proxy *real* wikipedia over the network from the web on rm2 rather than rely on the local server.

**Comment by dps** [comment]
Would love to hear any feedback on what you'd like in that regard.

FYI What I tried to get sdard working:
* Put the USB port into host mode
```
reMarkable: ~/ cat /sys/kernel/debug/ci_hdrc.0/role 
gadget
reMarkable: ~/ echo host > /sys/kernel/debug/ci_hdrc.0/role
reMarkable: ~/ cat /sys/kernel/debug/ci_hdrc.0/role 
host
```
* turn on power to port
```
echo enabled > /sys/bus/usb/devices/usb1/power/wakeup
echo on > /sys/bus/usb/devices/usb1/power/control
```
```

**Comment by dps** [comment]
Fixed the rendering issues
